### PR TITLE
Update: Improved error handling and dusted off some corners to polish up the tutorial.

### PR DESCRIPTION
**Pull request by brighton-ifaya**
@jamesrp13 @CoachChuckFF

### CODE REVIEW

**Comment by jamesrp13** [comment]
@brighton-ifaya thanks for this! It's hard for me to see what the real changes are vs just linting changes. Any chance you could go through and comment the changes and why? Thanks!

**Comment by brighton-ifaya** [comment]
> @brighton-ifaya thanks for this! It's hard for me to see what the real changes are vs just linting changes. Any chance you could go through and comment the changes and why? Thanks!

Apologies. My formatter made a mess drowning out the real changes. Let me fix that.

**Comment by mikemaccana** [comment]
@jamesrp13 do you want to keep this at Unboxed or want us to move it to Foundation and manage reviews?

**Comment by mikemaccana** [comment]
@jamesrp13 I was thinking we'd move this to foundation like other course solution repos (plan is to eventually get them all into CI so we can test when solana CLI, Rust or Anchor break anything).

**Review by mikemaccana — APPROVED** [review]

**Pull request merged**
